import { bi } from '../components/bilingual/BilingualText';
import type { StoreCategory, StoreProduct } from './storeTypes';

export const previewCategories: StoreCategory[] = [
  {
    slug: 'swimming',
    name: bi('Swimming', 'السباحة'),
    description: bi('Olympic-grade swim goggles, caps, hydrodynamic fins and technique gear.', 'نظارات سباحة أولمبية، قبعات سيليكون، زعانف هيدروديناميكية ومعدات تدريب.'),
    accent: '#d4af37',
    hero: '/media/products/hero-banner.jpg',
  },
  {
    slug: 'football',
    name: bi('Football', 'كرة القدم'),
    description: bi('FIFA-spec match balls, aerodynamic apparel and disciplined training gear.', 'كرات مباريات معتمدة بمواصفات الفيفا، ملابس ديناميكية ومعدات تدريب احترافية.'),
    accent: '#3f9b66',
    hero: '/media/sports/football/football-01-hero.webp',
  },
  {
    slug: 'basketball',
    name: bi('Basketball', 'كرة السلة'),
    description: bi('Court competition basketballs and elite training accessories.', 'كرات سلة للمنافسات الرسمية ومستلزمات تدريب الملعب النخبوية.'),
    accent: '#c77a3b',
    hero: '/media/sports/basketball/basketball-01-shooting-technique.webp',
  },
  {
    slug: 'apparel',
    name: bi('Sportswear', 'الملابس الرياضية'),
    description: bi('Performance compression layers, shorts and track jackets designed for champions.', 'قمصان ضغط، شورتات تدريب وجاكيتات إحماء مصممة للأبطال.'),
    accent: '#d4af37',
    hero: '/media/products/jacket-black-gold.jpg',
  },
  {
    slug: 'accessories',
    name: bi('Accessories', 'الإكسسوارات'),
    description: bi('Athlete duffle bags, insulated hydration flasks, and daily training essentials.', 'حقائب رياضية فاخرة، زجاجات ترطيب معزولة، ومستلزمات التدريب اليومي.'),
    accent: '#9a6c15',
    hero: '/media/products/duffle-bag.jpg',
  },
  {
    slug: 'equipment',
    name: bi('Footwear & Gear', 'الأحذية والمعدات'),
    description: bi('Elite runner shoes, kickboards and performance training apparatus.', 'أحذية جري نخبوية، ألواح تدريب ومعدات تعزيز الأداء الرياضي.'),
    accent: '#58b9c5',
    hero: '/media/products/running-shoes.jpg',
  },
  {
    slug: 'tennis',
    name: bi('Tennis', 'التنس'),
    description: bi('Precision rackets, tournament grips and training accessories.', 'مضارب دقيقة، قبضات بطولات وإكسسوارات تدريب الملاعب.'),
    accent: '#9cbf45',
  },
  {
    slug: 'gymnastics',
    name: bi('Gymnastics', 'الجمباز'),
    description: bi('Flexibility apparel and foundational training accessories.', 'ملابس مرونة وإكسسوارات تدريب الحركات الأساسية.'),
    accent: '#8a66b6',
  },
  {
    slug: 'martial-arts',
    name: bi('Martial Arts', 'الفنون القتالية'),
    description: bi('Uniforms, protection and disciplined combat practice gear.', 'أزياء قتالية ومعدات حماية للتدريب المنضبط.'),
    accent: '#a95151',
  },
];

const blackGold = [bi('Black / Gold', 'أسود / ذهبي'), bi('White / Gold', 'أبيض / ذهبي')];

export const previewProducts: StoreProduct[] = [
  {
    id: 'uo-swim-goggles-pro',
    slug: 'elite-swim-goggles',
    name: bi('UO Aqua Speed Elite Swim Goggles', 'نظارة سباحة أكوا سبيد إيليت برو'),
    description: bi(
      'Olympic-standard hydrodynamic racing goggles with anti-fog mirror lenses, liquid silicone leak-proof seal, and interchangeable gold-accented nose bridges.',
      'نظارة سباحة هيدروديناميكية بمواصفات أولمبية مع عدسات عاكسة مضادة للضباب، حشية سيليكون سائلة مانعة للتسرب، وجسور أنف قابلة للتعديل بتطعيمات ذهبية.'
    ),
    category: 'swimming',
    type: bi('Swim Goggles', 'نظارات سباحة'),
    price: 120,
    currency: 'AED',
    sku: 'UO-SW-001',
    badge: 'featured',
    image: '/media/user-products/product_01.png',
    gallery: [
      '/media/user-products/product_01.png',
      '/media/user-products/product_04.png',
    ],
    colors: blackGold,
  },
  {
    id: 'uo-swim-cap-pro',
    slug: 'silicone-swim-cap',
    name: bi('UO Pro Silicone Swim Cap', 'قبعة سباحة سيليكون برو يو أو'),
    description: bi(
      '100% hypoallergenic high-grade silicone swim cap embossed with the United Olympics golden lion crest. Hydrodynamic contour reduces drag and protects hair from chlorinated water.',
      'قبعة سباحة سيليكون فائقة النقاء 100% منقوشة بشعار أسد يونايتد أولمبيكس الذهبي. تصميم انسيابي يقلل المقاومة ويحمي الشعر من مياه المسابح.'
    ),
    category: 'swimming',
    type: bi('Swim Caps', 'قبعات سباحة'),
    price: 45,
    currency: 'AED',
    sku: 'UO-SW-002',
    badge: 'new',
    image: '/media/user-products/product_03.png',
    gallery: [
      '/media/user-products/product_03.png',
      '/media/user-products/product_02.png',
    ],
    colors: blackGold,
  },
  {
    id: 'uo-hydro-training-fins',
    slug: 'training-fins',
    name: bi('UO Hydro-Dynamic Training Fins', 'زعانف تدريب هيدروديناميكية يو أو'),
    description: bi(
      'Dual-density silicone propulsion fins engineered to build leg power, improve ankle flexibility, and maintain an authentic racing kick cadence.',
      'زعانف دفع سيليكونية مزدوجة الكثافة مصممة لتعزيز قوة الساقين، تحسين مرونة الكاحل، ومحاكاة إيقاع الركل في السباقات الحقيقية.'
    ),
    category: 'swimming',
    type: bi('Training Equipment', 'معدات تدريب السباحة'),
    price: 210,
    currency: 'AED',
    sku: 'UO-SW-003',
    badge: 'featured',
    sizes: ['36-38', '39-41', '42-44', '45-47'],
    image: '/media/user-products/product_14.png',
    gallery: ['/media/user-products/product_14.png'],
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-training-kickboard',
    slug: 'training-kickboard',
    name: bi('UO High-Density Kickboard', 'لوح تدريب سباحة عالي الكثافة'),
    description: bi(
      'Ultra-buoyant closed-cell EVA foam kickboard with ergonomic grip handles and textured non-slip surface, designed for rigorous lower-body swimming sets.',
      'لوح سباحة مصنوع من رغوة EVA مغلقة الخلايا وعالية الطفو مع مقابض مريحة وسطح مضاد للانزلاق مخصص لتمارين الجزء السفلي من الجسم.'
    ),
    category: 'swimming',
    type: bi('Training Equipment', 'معدات تدريب'),
    price: 85,
    currency: 'AED',
    sku: 'UO-SW-004',
    image: '/media/user-products/product_15.png',
    gallery: ['/media/user-products/product_15.png'],
    colors: [bi('Matte Black / Gold', 'أسود مطفي / ذهبي')],
  },
  {
    id: 'uo-pro-match-ball',
    slug: 'training-football',
    name: bi('UO Pro Match Soccer Ball (FIFA Spec)', 'كرة قدم للمباريات الرسمية يو أو برو'),
    description: bi(
      'Official FIFA Quality Pro match ball featuring thermally bonded seamless 14-panel geometry, textured aerodynamic micro-grooves, and golden lion crest.',
      'كرة مباريات رسمية معتمدة بجودة FIFA برو تتميز بهيكل حراري مدمج غير مخيط من 14 قطعة، وتجاويف دقيقة لتحسين الديناميكية الهوائية وشعار ذهبي مميز.'
    ),
    category: 'football',
    type: bi('Match Balls', 'كرات مباريات'),
    price: 89,
    currency: 'AED',
    sku: 'UO-FB-001',
    badge: 'featured',
    image: '/media/user-products/product_05.png',
    gallery: [
      '/media/user-products/product_05.png',
      '/media/user-products/product_06.png',
    ],
    colors: blackGold,
  },
  {
    id: 'uo-training-top',
    slug: 'performance-training-top',
    name: bi('UO Compression Performance Jersey', 'قميص تدريب ضغط للأداء الرياضي'),
    description: bi(
      '4-way stretch moisture-wicking compression jersey with targeted ventilation zones, flatlock anti-chafe gold seams, and the United Olympics golden crest.',
      'قميص ضغط مرن رباعي الاتجاهات طارد للرطوبة مع مناطق تهوية مستهدفة ودرزات ذهبية مسطحة مضادة للاحتكاك وشعار أسد يونايتد أولمبيكس على الصدر.'
    ),
    category: 'apparel',
    type: bi('Performance Apparel', 'ملابس تدريب وأداء'),
    price: 149,
    currency: 'AED',
    sku: 'UO-AP-001',
    badge: 'featured',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: '/media/user-products/product_09.png',
    gallery: [
      '/media/user-products/product_09.png',
      '/media/user-products/product_08.png',
    ],
    colors: blackGold,
  },
  {
    id: 'uo-training-shorts',
    slug: 'performance-training-shorts',
    name: bi('UO Elite Performance Shorts', 'شورت تدريب للأداء الرياضي الفائق'),
    description: bi(
      'Lightweight breathable woven training shorts with gold racing side stripes, moisture-managing inner liner, zippered pocket, and custom gold-dipped drawstrings.',
      'شورت تدريب خفيف ومسامي بخطوط جانبية ذهبية، وبطانة داخلية لامتصاص الرطوبة، وجيب بسحاب للأغراض الثمينة، ورباط خصر مخصص بأطراف ذهبية.'
    ),
    category: 'apparel',
    type: bi('Training Shorts', 'شورتات تدريب'),
    price: 99,
    currency: 'AED',
    sku: 'UO-AP-002',
    badge: 'featured',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: '/media/user-products/product_10.png',
    gallery: [
      '/media/user-products/product_10.png',
      '/media/user-products/product_11.png',
    ],
    colors: blackGold,
  },
  {
    id: 'uo-pro-track-jacket',
    slug: 'pro-elite-training-jacket',
    name: bi('UO Pro Elite Training Track Jacket', 'جاكيت تدريب برو إيليت الرياضي'),
    description: bi(
      'Luxury warm-up track jacket constructed from weather-resistant double-knit interlock fabric with metallic gold hardware, high-stand collar, and tailored athletic silhouette.',
      'جاكيت إحماء فاخر مصنوع من قماش إنترلوك مزدوج الحياكة ومقاوم للعوامل الجوية مع سحابات معدنية ذهبية وياقة عالية وقصة رياضية أنيقة.'
    ),
    category: 'apparel',
    type: bi('Jackets & Outerwear', 'جاكيتات وملابس خارجية'),
    price: 289,
    currency: 'AED',
    sku: 'UO-AP-003',
    badge: 'new',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: '/media/user-products/product_12.png',
    gallery: ['/media/user-products/product_12.png'],
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-athlete-duffle-bag',
    slug: 'athlete-gym-bag',
    name: bi('UO Pro Athlete Duffle Bag', 'حقيبة دافل رياضية فاخرة للرياضيين'),
    description: bi(
      'Heavy-duty ballistic nylon gym and travel duffle featuring dedicated ventilated shoe compartment, water-resistant base, gold metal zippers, and padded ergonomic shoulder strap.',
      'حقيبة سفر ونادٍ رياضي من نايلون باليستي فائق التحمل مع حجرة أحذية مخصصة وجيدة التهوية، وقاعدة مقاومة للماء، وسحابات ذهبية وحزام كتف مبطن ومريح.'
    ),
    category: 'accessories',
    type: bi('Gym & Travel Bags', 'حقائب تدريب وسفر'),
    price: 179,
    currency: 'AED',
    sku: 'UO-AC-001',
    badge: 'featured',
    image: '/media/user-products/product_13.png',
    gallery: ['/media/user-products/product_13.png'],
    colors: [bi('Obsidian / Gold', 'أسود نفاث / ذهبي')],
  },
  {
    id: 'uo-insulated-bottle',
    slug: 'insulated-training-bottle',
    name: bi('UO Insulated Thermal Sports Bottle (750ml)', 'زجاجة رياضية حرارية معزولة يو أو (750 مل)'),
    description: bi(
      'Double-wall vacuum-insulated 18/8 pro stainless steel bottle that keeps fluids ice-cold for 24 hours or hot for 12 hours. Features leak-proof sport spout and golden crest.',
      'زجاجة فولاذ مقاوم للصدأ 18/8 معزولة بالفراغ مزدوج الجدار تحافظ على البرودة لمدة 24 ساعة والحرارة لمدة 12 ساعة، مع فوهة شرب رياضية مانعة للتسرب وشعار ذهبي.'
    ),
    category: 'accessories',
    type: bi('Hydration & Flasks', 'زجاجات وترطيب'),
    price: 69,
    currency: 'AED',
    sku: 'UO-AC-002',
    image: '/media/user-products/product_16.png',
    gallery: ['/media/user-products/product_16.png'],
    colors: [bi('Matte Black / Gold', 'أسود مطفي / ذهبي')],
  },
  {
    id: 'uo-gold-goggles',
    slug: 'uo-gold-goggles',
    name: bi('UO Gold-Mirrored Competition Goggles', 'نظارات المنافسة الذهبية العاكسة'),
    description: bi('Olympic-grade hydrodynamic goggles with premium gold-mirror coating.', 'نظارات هيدروديناميكية بمستوى الأولمبياد مع طلاء مرآة ذهبي فاخر.'),
    category: 'swimming',
    type: bi('Swim Goggles', 'نظارات سباحة'),
    price: 135,
    currency: 'AED',
    sku: 'UO-SW-G01',
    badge: 'new',
    image: '/media/products/gold_swim_goggles_1788602294440.jpg',
    colors: [bi('Gold', 'ذهبي')],
  },
  {
    id: 'uo-white-gold-goggles',
    slug: 'uo-white-gold-goggles',
    name: bi('UO White-Gold Racing Goggles', 'نظارات السباق البيضاء الذهبية'),
    description: bi('Sleek white racing frames paired with precision gold-mirrored lenses.', 'إطارات سباق بيضاء أنيقة متطابقة مع عدسات عاكسة ذهبية دقيقة.'),
    category: 'swimming',
    type: bi('Swim Goggles', 'نظارات سباحة'),
    price: 140,
    currency: 'AED',
    sku: 'UO-SW-G02',
    badge: 'featured',
    image: '/media/products/white_gold_goggles_1788602316154.jpg',
    colors: [bi('White / Gold', 'أبيض / ذهبي')],
  },
  {
    id: 'uo-match-ball-white',
    slug: 'uo-match-ball-white',
    name: bi('UO Premium Match Ball (Ice White)', 'كرة المباريات الفاخرة (أبيض جليدي)'),
    description: bi('Thermally bonded tournament-grade match ball featuring geometric paneling.', 'كرة مباريات معتمدة للبطولات مدمجة حرارياً تتميز بألواح هندسية.'),
    category: 'football',
    type: bi('Match Balls', 'كرات مباريات'),
    price: 95,
    currency: 'AED',
    sku: 'UO-FB-B01',
    badge: 'featured',
    image: '/media/products/uo_match_ball_white_1788602330644.jpg',
    colors: [bi('White / Gold', 'أبيض / ذهبي')],
  },
  {
    id: 'uo-match-ball-black',
    slug: 'uo-match-ball-black',
    name: bi('UO Premium Match Ball (Stealth Black)', 'كرة المباريات الفاخرة (أسود نفاث)'),
    description: bi('Tournament-grade match ball in obsidian black and elegant gold trim.', 'كرة مباريات بجودة البطولات باللون الأسود النفاث مع حواف ذهبية أنيقة.'),
    category: 'football',
    type: bi('Match Balls', 'كرات مباريات'),
    price: 95,
    currency: 'AED',
    sku: 'UO-FB-B02',
    badge: 'new',
    image: '/media/products/uo_match_ball_black_1788602346335.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-swim-cap-black',
    slug: 'uo-swim-cap-black',
    name: bi('UO Silicone Pro Swim Cap (Matte Black)', 'قبعة سباحة سيليكون برو (أسود مطفي)'),
    description: bi('Hydrodynamic silicone cap featuring the signature gold crest.', 'قبعة سباحة سيليكون هيدروديناميكية تتميز بشعار الأسد الذهبي المميز.'),
    category: 'swimming',
    type: bi('Swim Caps', 'قبعات سباحة'),
    price: 49,
    currency: 'AED',
    sku: 'UO-SW-C01',
    image: '/media/products/uo_swim_cap_black_1788602360225.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-swim-cap-white',
    slug: 'uo-swim-cap-white',
    name: bi('UO Silicone Pro Swim Cap (Ice White)', 'قبعة سباحة سيليكون برو (أبيض جليدي)'),
    description: bi('High-durability racing cap in pristine white with gold emblem.', 'قبعة سباحة عالية المتانة بلون أبيض ناصع مع شعار ذهبي.'),
    category: 'swimming',
    type: bi('Swim Caps', 'قبعات سباحة'),
    price: 49,
    currency: 'AED',
    sku: 'UO-SW-C02',
    image: '/media/products/uo_swim_cap_white_1788602374799.jpg',
    colors: [bi('White / Gold', 'أبيض / ذهبي')],
  },
  {
    id: 'uo-jersey-black',
    slug: 'uo-jersey-black',
    name: bi('UO Championship Compression Jersey (Stealth Black)', 'قميص ضغط لبطولات النخبة (أسود)'),
    description: bi('4-way stretch moisture-wicking compression jersey with ventilation zones.', 'قميص ضغط مرن طارد للرطوبة رباعي الاتجاهات مع مناطق تهوية.'),
    category: 'apparel',
    type: bi('Performance Apparel', 'ملابس تدريب وأداء'),
    price: 155,
    currency: 'AED',
    sku: 'UO-AP-J01',
    badge: 'featured',
    sizes: ['S', 'M', 'L', 'XL'],
    image: '/media/products/uo_jersey_black_1788602397846.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-jersey-white',
    slug: 'uo-jersey-white',
    name: bi('UO Championship Compression Jersey (Ice White)', 'قميص ضغط لبطولات النخبة (أبيض)'),
    description: bi('Ultra-breathable performance top with golden flatlock seams.', 'قميص أداء فائق التهوية مع درزات مسطحة ذهبية.'),
    category: 'apparel',
    type: bi('Performance Apparel', 'ملابس تدريب وأداء'),
    price: 155,
    currency: 'AED',
    sku: 'UO-AP-J02',
    badge: 'new',
    sizes: ['S', 'M', 'L', 'XL'],
    image: '/media/products/uo_jersey_white_1788602413628.jpg',
    colors: [bi('White / Gold', 'أبيض / ذهبي')],
  },
  {
    id: 'uo-shorts-black',
    slug: 'uo-shorts-black',
    name: bi('UO Elite Training Shorts (Stealth Black)', 'شورت تدريب للأداء الرياضي (أسود)'),
    description: bi('Lightweight woven training shorts with gold-accented drawstrings.', 'شورت تدريب منسوج خفيف الوزن مع أربطة مزينة بالذهب.'),
    category: 'apparel',
    type: bi('Training Shorts', 'شورتات تدريب'),
    price: 105,
    currency: 'AED',
    sku: 'UO-AP-S01',
    sizes: ['S', 'M', 'L', 'XL'],
    image: '/media/products/uo_shorts_black_1788602425759.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-shorts-white',
    slug: 'uo-shorts-white',
    name: bi('UO Elite Training Shorts (Ice White)', 'شورت تدريب للأداء الرياضي (أبيض)'),
    description: bi('Premium sportswear training shorts in pristine white.', 'شورت تدريب رياضي مميز بلون أبيض ناصع.'),
    category: 'apparel',
    type: bi('Training Shorts', 'شورتات تدريب'),
    price: 105,
    currency: 'AED',
    sku: 'UO-AP-S02',
    sizes: ['S', 'M', 'L', 'XL'],
    image: '/media/products/uo_shorts_white_1788602439716.jpg',
    colors: [bi('White / Gold', 'أبيض / ذهبي')],
  },
  {
    id: 'uo-jacket-black',
    slug: 'uo-jacket-black',
    name: bi('UO Pro Elite Windrunner Jacket', 'جاكيت وايند رانر إيليت للمحترفين'),
    description: bi('Weatherproof outer layer designed for pre-game warmth and comfort.', 'سترة واقية من الرياح ومقاومة للعوامل الجوية مصممة للإحماء.'),
    category: 'apparel',
    type: bi('Jackets & Outerwear', 'جاكيتات وملابس خارجية'),
    price: 295,
    currency: 'AED',
    sku: 'UO-AP-JK01',
    badge: 'new',
    sizes: ['S', 'M', 'L', 'XL'],
    image: '/media/products/uo_jacket_black_1788602453148.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-duffle-bag-ballistic',
    slug: 'uo-duffle-bag-ballistic',
    name: bi('UO Heavy-Duty Ballistic Duffle Bag', 'حقيبة دافل باليستية شديدة التحمل'),
    description: bi('Maximum-capacity athlete bag with ventilated shoe pocket.', 'حقيبة رياضية عالية السعة مع جيب أحذية مخصص وجيد التهوية.'),
    category: 'accessories',
    type: bi('Gym & Travel Bags', 'حقائب تدريب وسفر'),
    price: 185,
    currency: 'AED',
    sku: 'UO-AC-B01',
    badge: 'featured',
    image: '/media/products/uo_duffle_bag_1788602466489.jpg',
    colors: [bi('Obsidian / Gold', 'أسود نفاث / ذهبي')],
  },
  {
    id: 'uo-swim-fins-propulsion',
    slug: 'uo-swim-fins-propulsion',
    name: bi('UO Hydro-Propulsion Training Fins', 'زعانف تدريب هيدرو برو للدفع'),
    description: bi('Dual-density training fins designed to build lower-body strength.', 'زعانف تدريب مزدوجة الكثافة مصممة لزيادة قوة الجزء السفلي.'),
    category: 'swimming',
    type: bi('Training Equipment', 'معدات تدريب'),
    price: 215,
    currency: 'AED',
    sku: 'UO-SW-F01',
    sizes: ['38-40', '41-43', '44-46'],
    image: '/media/products/uo_swim_fins_1788602487150.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
  {
    id: 'uo-kickboard-eva',
    slug: 'uo-kickboard-eva',
    name: bi('UO Closed-Cell EVA Kickboard', 'لوح تدريب عالي الطفو من أسيتات إيفا'),
    description: bi('Buoyant training kickboard with anti-slip textured grip.', 'لوح تدريب سباحة عالي الطفو مع قبضة مريحة ومقاومة للانزلاق.'),
    category: 'swimming',
    type: bi('Training Equipment', 'معدات تدريب'),
    price: 89,
    currency: 'AED',
    sku: 'UO-SW-K01',
    image: '/media/products/uo_kickboard_1788602504166.jpg',
    colors: [bi('Matte Black / Gold', 'أسود مطفي / ذهبي')],
  },
  {
    id: 'uo-bottle-insulated',
    slug: 'uo-bottle-insulated',
    name: bi('UO Double-Wall Insulated Flask', 'قارورة مياه حرارية معزولة'),
    description: bi('18/8 food-grade stainless steel bottle keeping beverages ice-cold.', 'قارورة مياه من الفولاذ المقاوم للصدأ تحفظ البرودة طوال اليوم.'),
    category: 'accessories',
    type: bi('Hydration & Flasks', 'زجاجات وترطيب'),
    price: 75,
    currency: 'AED',
    sku: 'UO-AC-FL01',
    image: '/media/products/uo_bottle_1788602519756.jpg',
    colors: [bi('Matte Black / Gold', 'أسود مطفي / ذهبي')],
  },
  {
    id: 'uo-basketball-court',
    slug: 'uo-basketball-court',
    name: bi('UO Official Court Basketball', 'كرة سلة معتمدة للملاعب'),
    description: bi('Composite leather match basketball engineered for elite grip.', 'كرة سلة من الجلد المركب مخصصة للمباريات وتضمن ثبات اليد.'),
    category: 'basketball',
    type: bi('Basketball Equipment', 'معدات كرة السلة'),
    price: 195,
    currency: 'AED',
    sku: 'UO-BB-B01',
    badge: 'new',
    image: '/media/products/uo_basketball_1788602536173.jpg',
    colors: [bi('Gold / Black', 'أسود / ذهبي')],
  },
  {
    id: 'uo-running-shoes-elite',
    slug: 'uo-running-shoes-elite',
    name: bi('UO Elite Streak Running Shoes (Carbon Plate)', 'حذاء الجري النخبوي إيليت ستريك'),
    description: bi('High-rebound running shoes featuring responsive foam and carbon plate.', 'حذاء جري نخبوي مرتد للغاية يتميز برغوة تفاعلية ولوح كربون.'),
    category: 'equipment',
    type: bi('Footwear & Gear', 'الأحذية والمعدات'),
    price: 450,
    currency: 'AED',
    sku: 'UO-EQ-S01',
    badge: 'featured',
    sizes: ['41', '42', '43', '44', '45'],
    image: '/media/products/uo_running_shoes_1788602556010.jpg',
    colors: [bi('Black / Gold', 'أسود / ذهبي')],
  },
];
